---
version: 2.1
orbs:
  samvera: samvera/circleci-orb@1.0
jobs:
  bundle_and_test:
    parameters:
      ruby_version:
        type: string
      bundler_version:
        type: string
        default: 2.3.26
    executor:
      name: 'samvera/ruby'
      ruby_version: << parameters.ruby_version >>
    environment:
      WAIT_FOR_JEKYLL: 1
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    steps:
      - samvera/cached_checkout
      - run:
          name: Check for a branch named 'master'
          command: |
            git fetch --all --quiet --prune --prune-tags
            if [[ -n "$(git branch --all --list master */master)" ]]; then
              echo "A branch named 'master' was found. Please remove it."
              echo "$(git branch --all --list master */master)"
            fi
            [[ -z "$(git branch --all --list master */master)" ]]
      - run:
          name: Ensure that libxslt is installed for the nokogiri gem
          command: |
            sudo apt-get update && sudo apt-get install -y libxslt1.1 libxslt1-dev pkg-config
      - samvera/bundle:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
      - persist_to_workspace:
          root: ~/
          paths:
          - project/*
          - project/**/*
      - samvera/parallel_rspec

workflows:
  version: 2
  ci:
    jobs:
      - bundle_and_test:
          name: ruby3-2
          ruby_version: 3.2.2
          bundler_version: 2.3.26
      - bundle_and_test:
          name: ruby3-1
          ruby_version: 3.1.4
      - bundle_and_test:
          name: ruby3-0
          ruby_version: 3.0.6

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - bundle_and_test:
          name: ruby3-2
          ruby_version: 3.2.2
          bundler_version: 2.3.26
      - bundle_and_test:
          name: ruby3-1
          ruby_version: 3.1.4
      - bundle_and_test:
          name: ruby3-0
          ruby_version: 3.0.6
